method: random
metric:
  name: val_accuracy
  goal: maximize
parameters:
  batch_size:
    values: [16,32,64]
  embedding_size:
    distribution: q_uniform
    q: 128
    min: 128
    max: 1024
  hidden_size:
    distribution: q_uniform
    q: 128
    min: 128
    max: 2048
  source_attention_heads:
    values: [1,2,4]
  num_layers:
    values: [2,3]

 
